#!/bin/bash

echo "========================================="
echo "GitHub App Private Key Encoder for Vercel"
echo "========================================="
echo ""
echo "1. Get your private key from:"
echo "   https://github.com/settings/apps/YOUR_APP_NAME"
echo ""
echo "2. Save it to a file (e.g., private-key.pem)"
echo ""
echo "3. Run: cat private-key.pem | base64 | tr -d '\n'"
echo ""
echo "4. Copy the output and set it as GITHUB_APP_PRIVATE_KEY_B64 in Vercel"
echo ""
echo "========================================="
echo "Quick command (if you have the key file):"
echo ""
echo "cat private-key.pem | base64 | tr -d '\\n' | pbcopy"
echo "(This copies the base64 to your clipboard)"
echo ""
